### ISSUE TITLE
OSError: [Errno 22] Invalid argument

### ISSUE THREAD

**Issue by aifuenzalida** [Thammus/instaloader#30]
```
D:\instaloader>instaloader --login=aifuenzalidag alejandraa_maartinez18 --stories-only
Loaded session from c:\users\alvaro\appdata\local\temp/.instaloader-alvaro/session-aifuenzalidag.
Logged in as aifuenzalidag.
alejandraa_maartinez18/2017-07-27_18-06-57_UTC_profile_pic.jpg already exists
Retrieving stories from profile alejandraa_maartinez18.
[  1/  5] Traceback (most recent call last):
  File "C:\Users\Alvaro\AppData\Local\Programs\Python\Python36-32\Scripts\instaloader-script.py", line 11, in <module>
    load_entry_point('instaloader==2.2.2', 'console_scripts', 'instaloader')()
  File "c:\users\alvaro\appdata\local\programs\python\python36-32\lib\site-packages\instaloader.py", line 1201, in main
    args.fast_update, args.stories, args.stories_only)
  File "c:\users\alvaro\appdata\local\programs\python\python36-32\lib\site-packages\instaloader.py", line 1074, in download_profiles
    geotags, download_comments, fast_update, stories, stories_only)
  File "c:\users\alvaro\appdata\local\programs\python\python36-32\lib\site-packages\instaloader.py", line 954, in download
    download_videos=download_videos, fast_update=fast_update)
  File "c:\users\alvaro\appdata\local\programs\python\python36-32\lib\site-packages\instaloader.py", line 718, in download_stories
    date = datetime.fromtimestamp(date_float)
OSError: [Errno 22] Invalid argument
```

**Comment by aandergr** [comment]
Thanks for reporting. Commit 9eddc03 might fix this issue.
