### ISSUE TITLE
JSON Query to graphql/query: HTTP error code 502.

### ISSUE THREAD

**Issue by MatthieuBonenfant** [Thammus/instaloader#31]
Just hit that error from branch v3-dev (while doing my regular daily downloads)

```
[790] #starwarscosplay #starwarscosplay/its.just.a_spark_2017-08-08_17-51-47.jpg [My almost finished mando twi'…]
JSON Query to graphql/query: HTTP error code 502. [retrying]
Traceback (most recent call last):
  File "c:\python\scripts\instaloader-script.py", line 11, in <module>
    load_entry_point('instaloader==3.0rc0', 'console_scripts', 'instaloader')()
  File "c:\python\lib\site-packages\instaloader.py", line 1224, in main
    args.profile_pic_only, args.fast_update, args.stories, args.stories_only)
  File "c:\python\lib\site-packages\instaloader.py", line 1039, in main
    self.download_hashtag(hashtag=pentry[1:], max_count=max_count, fast_update=fast_update)
  File "c:\python\lib\site-packages\instaloader.py", line 852, in download_hashtag
    for post in self.get_hashtag_posts(hashtag):
  File "c:\python\lib\site-packages\instaloader.py", line 834, in get_hashtag_posts
    lambda d: d['data']['hashtag']['edge_hashtag_to_media'])
  File "c:\python\lib\site-packages\instaloader.py", line 340, in graphql_node_list
    edge_struct = edge_extractor(data)
  File "c:\python\lib\site-packages\instaloader.py", line 834, in <lambda>
    lambda d: d['data']['hashtag']['edge_hashtag_to_media'])
TypeError: 'NoneType' object is not subscriptable
```

**Comment by aandergr** [comment]
Thanks for testing our `v3-dev` branch and reporting this! Commit 5732948 changes Instaloader's behavior such that this kind of error should be handled differently. Instead of failing and aborting, a error message is printed and Instaloader goes on to the next node to download.

However, I am curious which error message would occur now. I somehow feel this is related to the rate limit issues, #26 and #29.
