### ISSUE TITLE
JSON dencoding fails

### ISSUE THREAD

**Issue by jtauert** [Thammus/instaloader#62]
Hi there,

I'm getting this error every time I'm loading stories. This error does not pop up when I'm only load regular images from profiles. 
```bash
Traceback (most recent call last):
  File "/usr/local/bin/instaloader", line 11, in <module>
    load_entry_point('instaloader==3.2.1', 'console_scripts', 'instaloader')()
  File "/usr/local/lib/python3.6/dist-packages/instaloader.py", line 1548, in main
    args.profile_pic_only, args.fast_update, args.stories, args.stories_only, args.only_if)
  File "/usr/local/lib/python3.6/dist-packages/instaloader.py", line 1388, in main
    filter_func=filter_func)
  File "/usr/local/lib/python3.6/dist-packages/instaloader.py", line 1254, in download_profile
    profile_metadata = self.get_profile_metadata(name)
  File "/usr/local/lib/python3.6/dist-packages/instaloader.py", line 1217, in get_profile_metadata
    return self.get_json('{}/'.format(profile_name), params={'__a': 1})
  File "/usr/local/lib/python3.6/dist-packages/instaloader.py", line 570, in get_json
    resp_json = resp.json()
  File "/home/julian/.local/lib/python3.6/site-packages/requests/models.py", line 892, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3/dist-packages/simplejson/__init__.py", line 516, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.scanner.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

The way of calling instaloader is this:
```bash
instaloader --login=<name> --password=<pw> --stories --fast-update `shuf namelist.txt`
```

Maybe there is a character in the text/description in a story that can not be decoded?

**Comment by Thammus** [comment]
Hi,
this bug is very difficult to reproduce because the profile or post which causes the exception is unknown to us. Besides, the python module "simplejson" (to which the thrown exception belongs) is not intended to be used with/by Instaloader. Could you please uninstall/remove the python package "simplejson" from your system and try it again? At least, that should cause another error message.

**Comment by jtauert** [comment]
Hi @Thammus,

this is strange. I uninstalled simplejson and instaloader works fine again. 
For anyone who has the same issue on Ubuntu, remove `simplejson` by running `sudo apt remove python3-simplejson`.

Tank you! :slightly_smiling_face:

**Comment by aandergr** [comment]
Thanks @jtauert for reporting this bug! Requests, the library we use as HTTP client, uses `simplejson` if it is installed rather than Python's own, well-functioning JSON implementation. `simplejson` seems to be known for decoding-related problems and its removal is discussed in requests/requests#3052, however not yet implemented in the current requests version. So at the moment, we advice to not have `simplejson` installed.
