### ISSUE TITLE
Problem with login

### ISSUE THREAD

**Issue by aifuenzalida** [Thammus/instaloader#66]
I got this error
```
Traceback (most recent call last):
  File "c:\users\alvaro\appdata\local\programs\python\python36-32\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\alvaro\appdata\local\programs\python\python36-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Alvaro\AppData\Local\Programs\Python\Python36-32\Scripts\instaloader.exe\__main__.py", line 9, in <module>
  File "c:\users\alvaro\appdata\local\programs\python\python36-32\lib\site-packages\instaloader.py", line 1548, in main
    args.profile_pic_only, args.fast_update, args.stories, args.stories_only, args.only_if)
  File "c:\users\alvaro\appdata\local\programs\python\python36-32\lib\site-packages\instaloader.py", line 1336, in main
    self.load_session_from_file(username, sessionfile)
  File "c:\users\alvaro\appdata\local\programs\python\python36-32\lib\site-packages\instaloader.py", line 854, in load_session_from_file
    session.cookies = requests.utils.cookiejar_from_dict(pickle.load(sessionfile))
_pickle.UnpicklingError: invalid load key, '\x00'.
```
And I am unable to download info using my login data (private profiles and stories)

**Comment by aandergr** [comment]
This looks like an error during loading of the session file. Maybe that file is corrupted. Did you try deleting the session file and then logging in again? The path of the session file is printed with `instaloader --help` at _Login (Download Private Profiles)_ -> _-f SESSIONFILE_. Alternatively you may change the session file path with `-f` and thereby create a new file, i.e. `instaloader -f sessionfile -l username profile-to-download ...`

**Comment by aifuenzalida** [comment]
@aandergr sorry for the delay, but you're right: the session file was corrupted. Deleted and executing again the script, put the password and voila!
